openapi: 3.0.1
info:
  title: swagger
  version: v1
paths:
  /api/aws/translate:
    get:
      tags:
        - AWS
      parameters:
        - name: text
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
  /api/aws/downloadThesis:
    get:
      tags:
        - AWS
      parameters:
        - name: thesisId
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/aws/uploadThesis:
    post:
      tags:
        - AWS
      parameters:
        - name: thesisId
          in: query
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: byte
            encoding:
              file:
                style: form
      responses:
        '200':
          description: Success
  /api/aws/deleteThesis:
    delete:
      tags:
        - AWS
      parameters:
        - name: thesisId
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/theses/supervisedByField:
    get:
      tags:
        - Theses
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupervisedThesisDtoFieldOfStudyInitialTableDto'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupervisedThesisDtoFieldOfStudyInitialTableDto'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SupervisedThesisDtoFieldOfStudyInitialTableDto'
  /api/theses/supervised:
    get:
      tags:
        - Theses
      parameters:
        - name: fieldOfStudyId
          in: query
          schema:
            type: integer
            format: int32
        - name: yearOfDefence
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SupervisedThesisDtoPagedResultDto'
            application/json:
              schema:
                $ref: '#/components/schemas/SupervisedThesisDtoPagedResultDto'
            text/json:
              schema:
                $ref: '#/components/schemas/SupervisedThesisDtoPagedResultDto'
components:
  schemas:
    SupervisedThesisDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        englishName:
          type: string
          nullable: true
        supervisorAcademicDegree:
          type: string
          nullable: true
        supervisorFullName:
          type: string
          nullable: true
        reviewerAcademicDegree:
          type: string
          nullable: true
        reviewerFullName:
          type: string
          nullable: true
        studentFullName:
          type: string
          nullable: true
      additionalProperties: false
    SupervisedThesisDtoFieldOfStudyInitialTableDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          nullable: true
        degree:
          type: integer
          format: int32
        studyForm:
          type: string
          nullable: true
        lectureLanguage:
          type: string
          nullable: true
        defenceYear:
          type: string
          nullable: true
        data:
          $ref: '#/components/schemas/SupervisedThesisDtoPagedResultDto'
      additionalProperties: false
    SupervisedThesisDtoPagedResultDto:
      type: object
      properties:
        currentPage:
          type: integer
          format: int64
        totalItems:
          type: integer
          format: int64
        hasNextPage:
          type: boolean
        results:
          type: array
          items:
            $ref: '#/components/schemas/SupervisedThesisDto'
          nullable: true
      additionalProperties: false
